jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"